
<?php $giftcardadd_url =$this->getUrl('ajax/ajax/giftcardadd/');?>
<div class="giftcard">
    <h2><?php echo $this->__('Gift Cards') ?></h2>
    <div id="giftcard_balance_lookup"></div>
    <span id="gc-please-wait" class="please-wait" style="display:none;">
        <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="" class="v-middle" /> <?php echo $this->__('Please wait, loading...') ?>
    </span>
    <form id="giftcard-form" action="javascript:void(0)" method="post">
       <?php /* <label for="giftcard_code"><?php echo $this->__('Gift Cards') ?></label>*/?>
        <div class="field-wrapper">
            <input class="required-entry input-text" type="text" id="giftcard_code" name="giftcard_code" value=""  placeholder="Gift Cards"/>
            <div class="button-wrapper">
                <button class="button2" onclick="estimateGiftCard('<?php echo $giftcardadd_url; ?>')" type="button" value="<?php echo $this->__('Apply') ?>"><span><span><?php echo $this->__('Apply') ?></span></span></button>
            </div>
        </div>
        <a class="button2 check-gc-status" onclick="checkGiftCardStatus();" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Check Gift Card status and balance')) ?>"><span><span><?php echo $this->__('Check Gift Card status and balance') ?></span></span></a>
    </form>

    <script type="text/javascript">
    //<![CDATA[
    var giftcardForm = new VarienForm('giftcard-form');
    function checkGiftCardStatus()
    {
        if (giftcardForm.validator && !giftcardForm.validator.validate()) {
            return false;
        }
        new Ajax.Updater(
            'giftcard_balance_lookup',
            '<?php echo Mage::getUrl('enterprise_giftcardaccount/cart/quickCheck') ?>',
            {
                onCreate: function() { $('gc-please-wait').show(); },
                onComplete: function() { $('gc-please-wait').hide(); },
                parameters : {giftcard_code : $('giftcard_code').value}
            }
        );
    }
	
	
	
	function estimateGiftCard(giftcardadd_url)
	 {
		jQuery('.giftcard #ajax_loader_estimate_update').show();
		jQuery.ajax({
				   type: 'post',
				   url: giftcardadd_url,
				   dataType:'json',
				   data: jQuery('#giftcard-form').serialize(),
				   beforeSend: function() {
						// Suspend the Checkout, showing a spinner...
						window.collector.checkout.api.suspend();
					},
				   success: function(data)
					{
						var result =  data;
						data_estimate_update_total = jQuery(result).find('div.totals').html();
						jQuery('div.totals').html(data_estimate_update_total);
							
							
						if(data.cart_content_ajax){
							jQuery('div.cart').replaceWith(data.cart_content_ajax);
						} 
						jQuery('.giftcard #ajax_loader_estimate_update').hide();
						
						
					},
					complete: function() {
						// ... and finally resume the Checkout after the backend call is completed to update the checkout
						window.collector.checkout.api.resume();
					},
		});
	 }
    //]]>
    </script>
	<span id='ajax_loader_estimate_update' style='display:none'><img src="<?php echo $this->getSkinUrl('images/collectorbank_ajax/ajax_loader.gif')?>" /></span>
</div>

